/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityCardSkeleton: typeof import('./src/components/ActivityCardSkeleton.vue')['default']
    ActivityFilterPopup: typeof import('./src/components/ActivityFilterPopup.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagFilter: typeof import('./src/components/TagFilter.vue')['default']
    TAvatar: typeof import('tdesign-mobile-vue')['Avatar']
    TButton: typeof import('tdesign-mobile-vue')['Button']
    TCalendar: typeof import('tdesign-mobile-vue')['Calendar']
    TCell: typeof import('tdesign-mobile-vue')['Cell']
    TCellGroup: typeof import('tdesign-mobile-vue')['CellGroup']
    TCheckbox: typeof import('tdesign-mobile-vue')['Checkbox']
    TCheckboxGroup: typeof import('tdesign-mobile-vue')['CheckboxGroup']
    TDateTimePicker: typeof import('tdesign-mobile-vue')['DateTimePicker']
    TDivider: typeof import('tdesign-mobile-vue')['Divider']
    TEmpty: typeof import('tdesign-mobile-vue')['Empty']
    TFooter: typeof import('tdesign-mobile-vue')['Footer']
    TForm: typeof import('tdesign-mobile-vue')['Form']
    TFormItem: typeof import('tdesign-mobile-vue')['FormItem']
    TGrid: typeof import('tdesign-mobile-vue')['Grid']
    TGridItem: typeof import('tdesign-mobile-vue')['GridItem']
    TIcon: typeof import('tdesign-mobile-vue')['Icon']
    TImage: typeof import('tdesign-mobile-vue')['Image']
    TIndexes: typeof import('tdesign-mobile-vue')['Indexes']
    TIndexesAnchor: typeof import('tdesign-mobile-vue')['IndexesAnchor']
    TInput: typeof import('tdesign-mobile-vue')['Input']
    TList: typeof import('tdesign-mobile-vue')['List']
    TLoading: typeof import('tdesign-mobile-vue')['Loading']
    TNavbar: typeof import('tdesign-mobile-vue')['Navbar']
    TPicker: typeof import('tdesign-mobile-vue')['Picker']
    TPopup: typeof import('tdesign-mobile-vue')['Popup']
    TPullDownRefresh: typeof import('tdesign-mobile-vue')['PullDownRefresh']
    TRadio: typeof import('tdesign-mobile-vue')['Radio']
    TRadioGroup: typeof import('tdesign-mobile-vue')['RadioGroup']
    TRate: typeof import('tdesign-mobile-vue')['Rate']
    TResult: typeof import('tdesign-mobile-vue')['Result']
    TSearch: typeof import('tdesign-mobile-vue')['Search']
    TSkeleton: typeof import('tdesign-mobile-vue')['Skeleton']
    TSlider: typeof import('tdesign-mobile-vue')['Slider']
    TSticky: typeof import('tdesign-mobile-vue')['Sticky']
    TSwiper: typeof import('tdesign-mobile-vue')['Swiper']
    TSwiperItem: typeof import('tdesign-mobile-vue')['SwiperItem']
    TSwitch: typeof import('tdesign-mobile-vue')['Switch']
    TTabBar: typeof import('tdesign-mobile-vue')['TabBar']
    TTabBarItem: typeof import('tdesign-mobile-vue')['TabBarItem']
    TTabPanel: typeof import('tdesign-mobile-vue')['TabPanel']
    TTabs: typeof import('tdesign-mobile-vue')['Tabs']
    TTag: typeof import('tdesign-mobile-vue')['Tag']
  }
}
