/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/[...all]': RouteRecordInfo<'/[...all]', '/:all(.*)', { all: ParamValue<true> }, { all: ParamValue<false> }>,
    '/activity-detail/[id]': RouteRecordInfo<'/activity-detail/[id]', '/activity-detail/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/buy-confirm/[id]': RouteRecordInfo<'/buy-confirm/[id]', '/buy-confirm/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/buy-result/[id]': RouteRecordInfo<'/buy-result/[id]', '/buy-result/:id', { id: ParamValue<true> }, { id: ParamValue<false> }>,
    '/main': RouteRecordInfo<'/main', '/main', Record<never, never>, Record<never, never>, '/main/base/' | '/main/user/'>,
    '/main/base/': RouteRecordInfo<'/main/base/', '/main/base', Record<never, never>, Record<never, never>>,
    '/main/user/': RouteRecordInfo<'/main/user/', '/main/user', Record<never, never>, Record<never, never>>,
    '/person-info/': RouteRecordInfo<'/person-info/', '/person-info', Record<never, never>, Record<never, never>>,
    '/select-location/': RouteRecordInfo<'/select-location/', '/select-location', Record<never, never>, Record<never, never>>,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the volar plugin to automatically type useRoute()
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes: '/'
      views: never
    }
    'src/pages/[...all].vue': {
      routes: '/[...all]'
      views: never
    }
    'src/pages/activity-detail/[id].vue': {
      routes: '/activity-detail/[id]'
      views: never
    }
    'src/pages/buy-confirm/[id].vue': {
      routes: '/buy-confirm/[id]'
      views: never
    }
    'src/pages/buy-result/[id].vue': {
      routes: '/buy-result/[id]'
      views: never
    }
    'src/pages/main.vue': {
      routes: '/main' | '/main/user/' | '/main/base/' | '/main/base' | '/main/user'
      views: 'default'
    }
    'src/pages/main/base/index.vue': {
      routes: '/main/base/'
      views: never
    }
    'src/pages/main/user/index.vue': {
      routes: '/main/user/'
      views: never
    }
    'src/pages/person-info/index.vue': {
      routes: '/person-info/'
      views: never
    }
    'src/pages/select-location/index.vue': {
      routes: '/select-location/'
      views: never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the volar plugin to automatically type useRoute()
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
