/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    ActivityCardSkeleton: typeof import('./../components/ActivityCardSkeleton.vue')['default']
    ActivityDetailPopup: typeof import('./../components/ActivityDetailPopup.vue')['default']
    ActivityFilterPopup: typeof import('./../components/ActivityFilterPopup.vue')['default']
    ChevronLeftIcon: typeof import('tdesign-icons-vue-next')['ChevronLeftIcon']
    CloseIcon: typeof import('tdesign-icons-vue-next')['CloseIcon']
    FilterIcon: typeof import('tdesign-icons-vue-next')['FilterIcon']
    LocationIcon: typeof import('tdesign-icons-vue-next')['LocationIcon']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TagFilter: typeof import('./../components/TagFilter.vue')['default']
    TButton: typeof import('tdesign-mobile-vue')['Button']
    TCalendar: typeof import('tdesign-mobile-vue')['Calendar']
    TCheckbox: typeof import('tdesign-mobile-vue')['Checkbox']
    TCheckboxGroup: typeof import('tdesign-mobile-vue')['CheckboxGroup']
    TDivider: typeof import('tdesign-mobile-vue')['Divider']
    TImage: typeof import('tdesign-mobile-vue')['Image']
    TList: typeof import('tdesign-mobile-vue')['List']
    TLoading: typeof import('tdesign-mobile-vue')['Loading']
    TNavbar: typeof import('tdesign-mobile-vue')['Navbar']
    TPopup: typeof import('tdesign-mobile-vue')['Popup']
    TRate: typeof import('tdesign-mobile-vue')['Rate']
    TResult: typeof import('tdesign-mobile-vue')['Result']
    TSearch: typeof import('tdesign-mobile-vue')['Search']
    TSkeleton: typeof import('tdesign-mobile-vue')['Skeleton']
    TSlider: typeof import('tdesign-mobile-vue')['Slider']
    TSticky: typeof import('tdesign-mobile-vue')['Sticky']
    TSwiper: typeof import('tdesign-mobile-vue')['Swiper']
    TSwiperItem: typeof import('tdesign-mobile-vue')['SwiperItem']
    TTabBar: typeof import('tdesign-mobile-vue')['TabBar']
    TTabBarItem: typeof import('tdesign-mobile-vue')['TabBarItem']
    TTabPanel: typeof import('tdesign-mobile-vue')['TabPanel']
    TTabs: typeof import('tdesign-mobile-vue')['Tabs']
  }
}
